name: Sync Preprod Repository with GCS Prod Bucket 

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
    inputs:
      trigger_sync:
        description: 'Whether to manually trigger a sync, otherwise only syncs pre-prod to prod with a 2 day delay'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: alpha
      - name: Install tools
        run: |
          sudo apt-get install -y jq
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: sync
        if: ${{ github.event.inputs.trigger_sync || env.trigger_sync == 'true' }}
        run: |
          # download preprod bucket and copy over to production bucket
          gcloud alpha --quiet storage cp -r ./build/* gs://jogolabs.xyz/tmp
