name: Sync Preprod Repository with GCS Prod Bucket 

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
    inputs:
      trigger_sync:
        description: 'Whether to manually trigger a sync, otherwise only syncs pre-prod to prod with a 2 day delay'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
    steps:
      - uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # v0.5.1
        with:
          project_id: project-rekor
          install_components: alpha
      # Setup OIDC->SA auth
      - uses: google-github-actions/auth@dafc92490a98acbdec38e6eb649f05d55e632447 # v0.7.2
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/237800849078/locations/global/workloadIdentityPools/root-signing-pool/providers/sigstore-root'
          service_account: 'sigstore-root-signing@project-rekor.iam.gserviceaccount.com'
          create_credentials_file: true
      - name: login
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth list
      - name: Install tools
        run: |
          sudo apt-get install -y jq
      - name: sync
        if: ${{ github.event.inputs.trigger_sync || env.trigger_sync == 'true' }}
        run: |
          # download preprod bucket and copy over to production bucket
          gcloud alpha --quiet storage cp -r gs://sigstore-preprod-tuf-root/ .

          # upload timestamp
          gcloud alpha --quiet storage cp --cache-control=no-store -r sigstore-preprod-tuf-root/*timestamp.json gs://sigstore-tuf-root/

          # delete any files present in sigstore-tuf-root not in sigstore-preprod-tuf-root
          gcloud alpha --quiet storage cp -r gs://sigstore-tuf-root/ .
