name: Deploy Website To GCS

on:
  push:
    branches:    
      - 'master'

jobs:
  sync:
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: alpha
      - name: Install tools
        run: |
          sudo apt-get install -y jq
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: CI="" npm run build
      - name: sync
        run: |
          # download preprod bucket and copy over to production bucket
          gcloud alpha --quiet storage rm -r gs://jogolabs.xyz/*
          gcloud alpha --quiet storage cp -r ./build/* gs://jogolabs.xyz/
